### ISSUE TITLE
Broken on iOS?

### ISSUE THREAD

**Issue by sweinertjr** [bradfrost/single-field-cc#11]
Anyone had an issue with this on iOS? After typing a card number, it doesn't transition properly to the MM/YY field and I can't complete the form.

**Comment by bradfrost** [comment]
Hey @sweinertjr, 
Thanks for letting me know about the issue. This repository actually isn't active anymore, so any issues should be directed at the [main repository](https://github.com/zdfs/toscani). It's worth stating that this began as more a proof of concept rather than a cross-browser/device tested solution, so there's definitely a lot of gotchas. Would love to see it evolve though!
